### ISSUE TITLE
Error running filter _extensions

### ISSUE THREAD

**Issue by Haly-en** [quarto-journals/plos#14]
If I use the command:
quarto render plos_one_articulo.qmd

I get this error: 

Error running filter _extensions/quarto-journals/plos/filter.lua:
_extensions/quarto-journals/plos/filter.lua:15: attempt to call a nil value (field 'is_format')
stack traceback:

**Comment by cderv** [comment]
Which quarto version are you using ? Thank you

**Comment by Haly-en** [comment]
my Quarto version is:
v1.2.313
 
now it's working if render the template.qmd. 
Thanks
